# Streamlit Cloud will read from here or from the web interface
OPENAI_API_KEY = "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"
CLAUDE_API_KEY = "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"
GROQ_API_KEY = "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"
PERPLEXITY_API_KEY = "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"
DEEPSEEK_API_KEY = "sk-bba69b9e3f4c40529602d89878f7b6fa"
GEMINI_API_KEY = "AIzaSyAqUkgm5svLOizf7b-keUIfIuMTT0jsgZA"